/**:
  ros__parameters:
    # esdf settings
    esdf_slice_height: 0.0
    esdf_2d_min_height: -0.1
    esdf_2d_max_height: 0.3
    # Lidar settings
    use_lidar: false
    # QoS settings
    depth_qos: "SENSOR_DATA"
    color_qos: "SENSOR_DATA"
    # Map clearing settings
    map_clearing_frame_id: "camera_link"
    # Rviz visualization
    slice_visualization_attachment_frame_id: "camera_link"
    
    # Needed because of RS driver bug:
    # https://github.com/IntelRealSense/realsense-ros/issues/2583
    is_realsense_data: True
