/**:
    ros__parameters:
      video_device: "/dev/right_fisheye"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "right_fisheye"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      image_width: 640
      image_height: 480
      camera_name: "right_fisheye"
      camera_info_url: "/workspaces/isaac_ros-dev/configs/camera_configs/right_fisheye/right_fisheye_camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1